Fix build break on macOS 10.13 no known conversion from (captured) lambda to function pointer
With this macOS 10.13 environment:

/usr/bin/g++ --version
  Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
                 --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
  Apple LLVM version 9.0.0 (clang-900.0.39.2)
  Target: x86_64-apple-darwin17.4.0
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I'm seeing this compile break:

g++ -c testsw.cpp -g -O $(sdl2-config --cflags) -std=c++11 -Wall -Wuninitialized -Wshadow -Wno-non-virtual-dtor -Wno-delete-non-virtual-dtor -Wno-multichar
testsw.cpp:113:19: error: no matching constructor for initialization of 'Button'
    start_but=new Button(bgwin,0,Rect(100,80,32,16),"stop",
                  ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./sdl-widgets.h:147:3: note: candidate constructor not viable: no known conversion from '(lambda at testsw.cpp:114:7)' to 'void (*)(Button *)' for 5th argument
  Button(WinBase *pw,Style,Rect,Label lab,void (*cmd)(Button*),const char *title=0);
  ^

testsw.cpp:351:5: error: no matching function for call to 'send_uev'
    send_uev([=](int) { printf("th_fun: n=%d\n",n); },0);
    ^~~~~~~~
./sdl-widgets.h:484:6: note: candidate function not viable: no known conversion from '(lambda at testsw.cpp:351:14)' to 'void (*)(int)' for 1st argument
void send_uev(void (*cmd)(int),int par);
     ^
2 errors generated.

According to https://stackoverflow.com/questions/28746744/passing-lambda-as-function-pointer, lambda's cannot be converted to function pointers if they capture under C++11.
In our case the two captures above in testsw.cpp are unnecessary as far as I can tell since they refer to scope-global variables or local static variables, both which should be visible within the lambda expression without capture.

Dropping the captures.